---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: managedfleetnotifications.ocmagent.managed.openshift.io
spec:
  group: ocmagent.managed.openshift.io
  names:
    kind: ManagedFleetNotification
    listKind: ManagedFleetNotificationList
    plural: managedfleetnotifications
    shortNames:
    - mfn
    singular: managedfleetnotification
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ManagedFleetNotification is the Schema for the managedfleetnotifications
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              fleetNotification:
                description: FleetNotification defines the desired spec of ManagedFleetNotification
                properties:
                  logType:
                    description: LogType is a categorization property that can be
                      used to group service logs for aggregation and managing notification
                      preferences.
                    type: string
                  name:
                    description: The name of the notification used to associate with
                      an alert
                    type: string
                  notificationMessage:
                    description: The body text of the Service Log notification when
                      the alert is active
                    type: string
                  references:
                    description: References useful for context or remediation - this
                      could be links to documentation, KB articles, etc
                    items:
                      pattern: ^https?:\/\/.+$
                      type: string
                    type: array
                  resendWait:
                    description: Measured in hours. The minimum time interval that
                      must elapse between active Service Log notifications
                    format: int32
                    type: integer
                  severity:
                    description: Re-use the severity definitation in managednotification_types
                    enum:
                    - Debug
                    - Info
                    - Warning
                    - Error
                    - Fatal
                    type: string
                  summary:
                    description: The summary line of the Service Log notification
                    type: string
                required:
                - name
                - notificationMessage
                - resendWait
                - severity
                - summary
                type: object
            required:
            - fleetNotification
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
